### ISSUE TITLE
Sidebar Friend View

### ISSUE THREAD

**Issue by asta12** [asta12/dh2642-project#24]
Sticky Sidebar which displays all friends.

You can also challenge a friend and see friend requests.

**Comment by asta12** [comment]
![image](https://user-images.githubusercontent.com/45568620/204862233-d118dde9-f347-4fe7-9d1c-4183fec6bdd8.png)

**Comment by alevarn** [comment]
Solved by #50 
and I created a new issue for connecting the sidebar to the friend profile view (see issue #59)
