### ISSUE TITLE
We want a global redirect to `/login`

### ISSUE THREAD

**Issue by alevarn** [asta12/dh2642-project#44]
Some pages should be protected such as `/profile`, `/profile/create-playlist`, etc. 
It would be good if we could add a global redirect to `/login` if we visit these pages without being logged-in.

**Comment by AnnaSkantz** [comment]
We have fixed the redirection on most files, so it is not really prioritized, but it would be nice if we have time.

**Comment by alevarn** [comment]
Solved by hiding navbar items.
