### ISSUE TITLE
Remove error printed to console

### ISSUE THREAD

**Issue by AnnaSkantz** [asta12/dh2642-project#45]
When we try to login using a valid email and password, but with a non-existing corresponding user, we get the following output to the console, see image below:

![image](https://user-images.githubusercontent.com/59956393/206173756-045b0679-d6ac-4c61-858c-22da5452fb57.png)
(ignore the first error in the console - that is always there for me)

For the final hand-in of the project we do not want any errors in the console and this does therefore need to be addressed before hand-in!

**Comment by alevarn** [comment]
It seems like this error comes from the Firebase library and not our code. I don't think we can fix this.

**Comment by AnnaSkantz** [comment]
I tried to look into this as well but didn't find a way to remove the error. I guess this issue can be closed?

**Comment by alevarn** [comment]
Yes we close this issue.
