### ISSUE TITLE
User evaluation: Sidebar

### ISSUE THREAD

**Issue by alevarn** [asta12/dh2642-project#73]
- It is easy to miss the sidebar tab, we need to make it more clear that it is clickable - perhaps shade the tab or write some text.
- He asked how to add friends after having looked at the sidebar. It was empty and just said friends. Maybe add message “You have no friends. Do this to get friends”

**Comment by AnnaSkantz** [comment]
It would also be good if we enabled a user to close the sidebar by clicking on the area outside the sidebar, instead of having to click on the X.

**Comment by AnnaSkantz** [comment]
Have a link to the sidebar from the profile page
